### ISSUE TITLE
Thx for the bible-mode fixes

### ISSUE THREAD

**Issue by OrionRandD** [fmgilham/lisp-logo#1]
Hi,
I couldn't access your bible-mode fork, but I want to give you thx for the fixes.
The original repo is full of bugs. And it seems kind of abandonware...
Keep up the good work...
If I had a better know-how in lisp, I would certainly try to help you...
God bless.

**Comment by fmgilham** [comment]
Hi! Thanks for the comment! Just yesterday my wife was suggesting that nobody in the world would ever use this program that I'm spending so much time on. :-) Then your email came to give me a bit of a boost.

Seriously, I use emacs for my workflow for doing talks and Sunday school lessons, and bible-mode is perfect for helping with that. I do a lot with the original languages in my preparation and I'm trying to make bible-mode a really effective tool for that.

I'm not sure what you meant by not being able to access the bible-mode fork. Would you happen to know what I have to do to make it available? I assume you were able to get the code?

**Comment by OrionRandD** [comment]
Thx for reaching out.
I also use Emacs a lot for all kinds of things, including teaching the Bible.
I use it, e.g., in my Bible study on Saturdays and have a few videos, using it elsewhere...
I am sure the time you've been investing on this program will be recompensated by the Lord himself, assuming that you're a Christian...

Here are some vids 
https://archive.org/details/@achy1les/
and here is my blog
https://cypher.codeberg.page/
If I was a Lisp wizard, I certainly would try to help you with this program as well.
You can ask advise in librechat IRC server on #emacs channel on how to submit your package to MELPA/ELPA and I am sure they will lead you on the right path. You can access librechat through ERC in Emacs itself or using other IRC package availaba on Elpa...
For me, Emacs is a God's given gift and we should use it to His glory...
Thx a lot for replying...

**Comment by fmgilham** [comment]
BTW I have a blog as well. It's [https://goodnews.homedns.org/]. Yes, I am a Christian.

**Comment by OrionRandD** [comment]
> BTW I have a blog as well. It's [https://goodnews.homedns.org/](https://goodnews.homedns.org). Yes, I am a Christian.
Me too... Beautiful blog!
God bless you...
